config/routes.rb
AcademiaCourse::Application.routes.draw do
  resources :users

  get 'courses/list_rank_humanity' => 'courses#list_rank_humanity'
  get 'courses/list_rank_nature' => 'courses#list_rank_nature'
  get 'courses/list_all' => 'courses#list_all'
  get 'about' => 'courses#about'
  get 'courses' => 'courses#list_all'
  resources :courses do
    resources :comments
  end
  

  root 'courses#list_all'

  get "/sign_out", to: "application#logout", as: :logout
  resources :user

  get "/sign_in", to: "application#login_with_cas", as: :login

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	#serialize :info, ActiveRecord::Coders::Hstore

#	after_create :set_info#

#	def set_info
#		if /F/ =~ self.school_id.to_s
#			self.grade = 0
#		else
#			/(..)/ =~ self.school_id.to_s
#			self.grade = $1
#		end
#	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action CASClient::Frameworks::Rails::GatewayFilter, only: :login_with_cas

  def login_with_cas
  	if User.find_by school_id: session[:cas_user]
    	@current_user = User.find_by school_id: session[:cas_user]
    else
  		@current_user = User.create!(
  				school_id: session[:cas_user].to_i,
  				name: session[:cas_user],
  				password: session[:cas_user]
  			)
    end
  	#end
  end

  def current_user
  	@current_user
  end

  def user_signed_in?
  	!@current_user.nil?
  end


  def logout
    CASClient::Frameworks::Rails::Filter.logout(self)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter CASClient::Frameworks::Rails::Filter, :login_with_cas

  def create
    @course = Course.find(params[:course_id])
    @comment = @course.comments.create(params[:comment].permit(:content))
    @comment.author_id = session[:cas_user]
    @comment.save
    redirect_to course_path(@course)
  end

  def index
  	redirect_to course_path(@course)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :set_courses, only: [:welcome, :list_rank_humanity, :list_rank_nature, :list_all, :index]
  before_action :check_dev, only: [:edit, :update, :new, :destroy]
  before_action CASClient::Frameworks::Rails::Filter, :login_with_cas, except: [:list_all , :list_rank_humanity , :list_rank_nature]

  def about
    
  end
  
  def welcome

  end

  def list_rank_humanity
    @courses = @courses.select { |e| e.ranking !=0 && e.subject == '人文' }
    @courses = @courses.sort_by { |e| e.ranking }
  end

  def list_rank_nature
    @courses = @courses.select { |e| e.ranking !=0 && e.subject == '自然' }
    @courses = @courses.sort_by { |e| e.ranking }
  end

  def list_all

  end

  def like
    
  end

  # GET /courses
  # GET /courses.json
  def index
    
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @comments = @course.comments
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    #if params[:course][:photo] and @course.photo
    #  old_photo = Course.find(params[:id]).photo
    #end
    #if @course.update_attributes(params[:course])
    #  old_photo.remove! if old_photo
    #end

    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    def set_courses
      @courses = Course.all
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:teacher, :photo, :title, :gpa, :grade, :intro_text, :gp_text, :difficulty_text, :features_text, :likes, :ranking, :subject, :room, :position, :stu_quantity)
    end

    def check_dev
      if Rails.env != "development"
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:grade, :type, :info, :name, :password, :salt, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.slim
= form_for @course do |f|
  - if @course.errors.any?
    #error_explanation
      h2 = "#{pluralize(@course.errors.count, "error")} prohibited this course from being saved:"
      ul
        - @course.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :teacher
    = f.text_field :teacher
  .field
    = f.label :photo
    = image_tag(@course.photo_url(:thumb)) if @course.photo?
    = f.file_field :photo
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :gpa
    = f.text_field :gpa
  .field
    = f.label :intro_text
    = f.text_area :intro_text
  .field
    = f.label :gp_text
    = f.text_area :gp_text
  .field
    = f.label :difficulty_text
    = f.text_area :difficulty_text
  .field
    = f.label :features_text
    = f.text_area :features_text
  .field
    = f.label :subject
    = f.text_field :subject
  .field
    = f.label :ranking
    = f.text_field :ranking
  .field
    = f.label :room
    = f.text_field :room
  .field
    = f.label :position
    = f.text_field :position
  .field
    = f.label :stu_quantity
    = f.text_field :stu_quantity
  .actions = f.submit 'Save'

app/views/courses/_help.html.slim
.acd.article-info-header
              .acd.title 帮助
.acd.article
  .description
    .text
      .content
        li
          a href='http://page.renren.com/601858190/channel-noteshow-922005615' Academia网站使用方法
        li
          a href='http://page.renren.com/601858190/channel-noteshow-922005729' 体育和艺术课程top5排名

app/views/courses/_list.html.slim
/disable turbolink because of error in BaiduShare <- so this is a WTF thing. fix it out!
ul.acd.list.page.data-no-turbolink
          - i = 0
          - for course in @courses
            li.acd.list.item
              - i = i + 1
              .number = i
              .content href="/courses/#{course.id}"
                .title
                  = link_to course.title, course_path(id: course), data: {no_turbolink: true}
                  - if Rails.env == 'development'
                    | &ensp;&ensp;
                    = link_to '(编辑', edit_course_path(course)
                    | &ensp;/&ensp;
                    = link_to '删除)', course, data: {:confirm => '你确定么？'}, :method => :delete
                .sub-title
                  = truncate(strip_tags(course.features_text), length: 60)

app/views/courses/edit.html.slim
javascript:
  $("#example-navbar .navbar-nav li a[href*='courses']").parent().addClass("active")
  
h1 Editing course

== render 'form'

= link_to 'Show', @course
'|
= link_to 'Back', courses_path

app/views/courses/index.html.slim
javascript:
  $("#example-navbar .navbar-nav li a[href*='courses']").parent().addClass("active")
  
h1 Listing courses

table
  tr
    th Teacher
    th Photo
    th Title
    th Gpa
    th Grade
    th Intro text
    th Gp text
    th Difficulty text
    th Features text
    th
    th
    th

  - @courses.each do |course|
    tr
      td = course.teacher
      td = image_tag(course.photo_url(:thumb)) if course.photo?
      td = course.title
      td = course.gpa
      td == course.intro_text
      td == course.gp_text
      td == course.difficulty_text
      td == course.features_text
      td = course.subject
      td = course.likes
      td = course.ranking
      td = link_to 'Show', course
      td = link_to 'Edit', edit_course_path(course)
      td = link_to 'Destroy', course, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Course', new_course_path

app/views/courses/list_all.html.slim
.col-md-10.col-md-offset-3
  .acd.page
    .acd.main.content
      .body
        .acd.article-info-header style="margin-bottom: 0; border-bottom: #ddd solid 1px;"
          .acd.title 课程总览
          .acd.subtitle
            |这里是Academia数据库内的全部课程，另有
            = link_to '人文课程排名', courses_list_rank_humanity_path
            |和
            = link_to '自然课程排名', courses_list_rank_nature_path
            |可供参考
        == render 'list'

app/views/courses/list_rank_humanity.html.slim
javascript:
  $("#example-navbar .navbar-nav li a[href*='courses']").parent().addClass("active")
  
.col-md-10.col-md-offset-3
  .acd.page
    .acd.main.content
      .body
        .acd.article-info-header style="margin-bottom: 0; border-bottom: #ddd solid 1px;"
          .acd.title 课程排名
          .acd.subtitle
          	|这里是Academia根据所得的主观、客观数据而作的人文课程排名，仅供参考。另有
          	= link_to '自然课程', courses_list_rank_nature_path
          	|排名。若想了解未入围的课程，请参考
          	= link_to '全部课程', courses_list_all_path
          	|页面
        == render 'list'

app/views/courses/list_rank_nature.html.slim
javascript:
  $("#example-navbar .navbar-nav li a[href*='courses']").parent().addClass("active")
  
.col-md-10.col-md-offset-3
  .acd.page
    .acd.main.content
      .body
        .acd.article-info-header style="margin-bottom: 0; border-bottom: #ddd solid 1px;"
          .acd.title 课程排名
          .acd.subtitle
          	|这里是Academia根据所得的主观、客观数据而作的自然课程排名，仅供参考。另有
          	= link_to '人文课程', courses_list_rank_humanity_path
          	|排名。若想了解未入围的课程，请参考
          	= link_to '全部课程', courses_list_all_path
          	|页面
        == render 'list'

app/views/courses/new.html.slim
javascript:
  $("#example-navbar .navbar-nav li a[href*='courses']").parent().addClass("active")
  
h1 New course

== render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.slim
javascript:
  $("#example-navbar .navbar-nav li a[href*='courses']").parent().addClass("active")
  
.container
  .row
    .col-md-10
      .acd.page
        .acd.main.content
          .header
            .labels
              a.text 课程介绍:
              = @course.title
          .body
            .title
              .content
                header.acd
                  h3.title
                    a.title = @course.title
                  span.sub.title
                    span.subject = @course.teacher
                    | 老师
                    | &nbsp;-&nbsp;
                    span.timeago = @course.room
              .acd.tip
                .items
                  .acd.item
                    span.acd.tip-holder
                    a.acd.tip-content.shadow 
                      |#
                      = @course.subject
              .acd.avatar
                  = image_tag(@course.photo_url(:thumb)) if @course.photo?
            .acd.article
              .description
                .text
                  .content
                    == @course.intro_text
            .acd.panel-group id="extend-text"
              .acd.panel.panel-default
                .panel-heading
                  h4.panel-title
                    a data-toggle="collapse" data-parent="#extend-text" href="#gpd" 刷积点难度&方法
                #gpd.panel-collapse.collapse class="in"
                  .panel-body == @course.gp_text
              .acd.panel.panel-default
                .panel-heading
                  h4.panel-title
                    a data-toggle="collapse" data-parent="#extend-text" href="#cd" 学知识难度&方法
                #cd.panel-collapse.collapse
                  .panel-body == @course.difficulty_text
              .acd.panel.panel-default
                .panel-heading
                  h4.panel-title
                    a data-toggle="collapse" data-parent="#extend-text" href="#ft" 特点
                #ft.panel-collapse.collapse
                  .panel-body == @course.features_text
            .acd.controller
              /= button_to "#{@course.likes}", { :controller => 'course', :action => 'like' }, { :class => "acd small red btn" }
              /.acd.small.red.btn style="margin-right:8px"
                /span.glyphicon.glyphicon-heart
                  /= @course.likes
              <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more">分享到：</a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网">人人网</a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信">微信</a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博">新浪微博</a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间">QQ空间</a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博">腾讯微博</a></div>
              <script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"16"},"share":{"bdSize":16},"image":{"viewList":["renren","weixin","tsina","qzone","tqq"],"viewText":"分享到：","viewSize":"16"}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
    .col-md-5.col-md-offset-1
      .acd.page
        .acd.comments.main.content
          .body
            == render 'help'
            .acd.article-info-header
              .acd.title 课程信息
            .acd.article
              .description
                .text
                  .content
                    li 课位：#{@course.position}
                    li 最大人数：#{@course.stu_quantity}
                    li 老师：#{@course.teacher}
                    li 教室：#{@course.room}
            .acd.article-info-header
              .acd.title 评论
              .acd.subtitle 如果你上过这门课或有意组团……
            .many.comments   
              .haha.this.is.the.main.things
                .here.we.go
                  .things.go.here
                     - for comment in @comments
                        .media
                          a.pull-left
                            = image_tag('avatar_blank.png')
                          .media.body
                            h5.media.heading = comment.author_id
                            = comment.content
              = form_for([@course, @course.comments.build], html: {class: "say something", style: "background-color: #eee;padding-top: 15px;"}) do |f|
                = f.text_area :content, :class => "acd"
                = f.submit '发布', :class => "acd small green btn"
    - if @course.ranking != 0
      .acd.float.tip style="top:55px;left:57%;"
        .logo
        .text
          span.text 排名：
          = @course.ranking

app/views/courses/welcome.html.slim
javascript:
  $("#example-navbar .navbar-nav li a[href='/']").parent().addClass("active")

.jumbotron
  .container
    h1 Welcome to Academia!
    
.container
  .row
    .acd.page
      .col-md-16
        .acd.main.content
          .body
            .title
              .content
                header.acd
                  h2.title Academia是什么
  .row
    .acd.page
      .col-md-5
        .acd.main.content
          .body
            .title
              .content
                header.acd
                  h2.title Academia是什么
      .col-md-4.col-md-offset-1
        .acd.main.content
          .body
            .title
              .content
                header.acd
                  h2.title Academia是什么
      .col-md-5.col-md-offset-1
        .acd.main.content
          .body
            .title
              .content
                header.acd
                  h2.title Academia是什么

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    title Academia
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "#{controller_name}", "data-turbolinks-track" => true 
    = csrf_meta_tags
  body class=("#{session[:cas_user]} #{controller_name} #{action_name} #{@current_user}") data-controller-name="#{controller_name} #{request.path}"
  	
  	nav.navbar.navbar-default.navbar-fixed-top.acd role="navigation"
	    .navbar-header
	      button.navbar-toggle type="button" id="mobile-menu" href="/"
	        span.sr-only NavBar 
	        span.icon-bar
	        span.icon-bar
	        span.icon-bar
	      a.navbar-brand.acd.logo href=root_path
	    .acd.collapse.navbar-collapse#example-navbar
	      ul.nav.navbar-nav.main
	        /li = link_to '首页', root_path
	        li class=('active' if controller_name == "courses" && request.path != '/about')
              = link_to '选课指南', courses_path
	        li class=('active' if request.path == '/about')
              = link_to '关于', about_path
	      ul.nav.navbar-nav.navbar-right
            - unless @current_user.nil?
              li
                a
                  | 欢迎您,
                  = @current_user.name
              li = link_to '登出', logout_path
            - else
              li = link_to "登陆", login_path
    == yield

    footer.acd
      .col-md-14.col-md-offset-1
                      p Website designed by <a href='https://github.com/timguoqk'>Qikun Guo</a> and <a href='https://github.com/cassiuschen'>Cassius Chen</a>, members of the <a href='http://www.thecmw.cn'>Creative Media Workshop</a>.
                      = debug(params) if Rails.env.development?

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :grade
    = f.number_field :grade
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :info
    = f.text_field :info
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :salt
    = f.text_field :salt
  .field
    = f.label :email
    = f.text_field :email
  .actions = f.submit 'Save'

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  tr
    th Grade
    th Type
    th Info
    th Name
    th Password
    th Salt
    th Email
    th
    th
    th

  - @users.each do |user|
    tr
      td = user.grade
      td = user.type
      td = user.info
      td = user.name
      td = user.password
      td = user.salt
      td = user.email
      td = link_to 'Show', user
      td = link_to 'Edit', edit_user_path(user)
      td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Grade:
  = @user.grade
p
  strong Type:
  = @user.type
p
  strong Info:
  = @user.info
p
  strong Name:
  = @user.name
p
  strong Password:
  = @user.password
p
  strong Salt:
  = @user.salt
p
  strong Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path